### ISSUE TITLE
日本語の変換がでてこない

### ISSUE THREAD

**Issue by okajun35** [gottadiveintopython/chumon_kesan_support#6]
moto g6 Plus  で試しましたが、キーボードで日本語キーボードが出てきませんでした。
SDL側の問題かもしれないです。
https://bugzilla.libsdl.org/show_bug.cgi?id=4775

**Comment by gottadiveintopython** [comment]
変換候補じゃなくて日本語キーボードそのものが出ないんですね。こっちでは出てくれるので原因の特定が難しいです。もし興味があったらですが、別の日本語入力ソフトを試してみるのもありかもしれないです。

**Comment by gottadiveintopython** [comment]
近々 別のAndroid端末を買うかもしれないので、その時に再現できれば直せるかもしれません。

**Comment by okajun35** [comment]
まだほかのキーボードを試していないですが。キーボードはGoogleキーボードです。ちなみに公式でだしているKivy Lancherでは日本語キーボードが出てきました
