### ISSUE TITLE
使い方の注意事項の下側が読めない

### ISSUE THREAD

**Issue by okajun35** [gottadiveintopython/chumon_kesan_support#7]
注意事項の下側の文字が読めないです。スクロールバーも出てきませんでした。Androidのバージョンは9になります

![p1](https://user-images.githubusercontent.com/14844237/67161650-73cdf700-f397-11e9-8e1e-09f5657f4a85.png)

**Comment by gottadiveintopython** [comment]
version0.0.2でスクロールできるようにします。
